#obs:
#  "obs":
#    label: Data

procs:
  
  misid:
    label: "Background"
  
  SMS-TStauStau_MStau-100_ctau-50mm_mLSP-1:
    label: "\\vtop{\\hbox{$m_{\\PSGt}(100)$}\\hbox{$c\\tau_{0}(50)$}}"
  SMS-TStauStau_MStau-100_ctau-100mm_mLSP-1:
    label: "\\vtop{\\hbox{$m_{\\PSGt}(100)$}\\hbox{$c\\tau_{0}(100)$}}"
  SMS-TStauStau_MStau-200_ctau-50mm_mLSP-1:
    label: "\\vtop{\\hbox{$m_{\\PSGt}(200)$}\\hbox{$c\\tau_{0}(50)$}}"
  SMS-TStauStau_MStau-200_ctau-100mm_mLSP-1:
    label: "\\vtop{\\hbox{$m_{\\PSGt}(200)$}\\hbox{$c\\tau_{0}(100)$}}"

syst_header: "Uncertainty source"

systematics:
  
  ren_scale:
    label: "$\\mu_{\\text{R}}$ scale"
  
  fac_scale:
    label: "$\\mu_{\\text{F}}$ scale"
  
  pdf:
    label: "\\vtop{\\hbox{Parton distribution}\\hbox{function}}"
  
  met_trigger:
    label: "$\\ptmiss$ trigger"
  
  distauid:
    label: "\\distau identification"
  
  jer:
    label: "Jet energy resolution"
  
  jes:
    label: "Jet energy scale"
  
  uncl_met:
    label: "\\vtop{\\hbox{$\\ptmiss$ unclustered}\\hbox{energy}}"

  #lumi_corr:
  #  label: "Luminosity (corr)"
  #
  #lumi_uncorr:
  #  label: "Luminosity (uncorr)"
  
  lumi:
    label: "Luminosity"
  
  #l1_prefiring:
  #  label: "L1 prefiring"
  
  pileup:
    label: "Pileup"
  
  fr_region:
    label: "\\vtop{\\hbox{Misid. probability}\\hbox{estimation region}}"
  
  fr_stat:
    label: "\\vtop{\\hbox{Misid. probability}\\hbox{statistics}}"

  fpred_alt:
    label: "\\vtop{\\hbox{Alternative bkg.}\\hbox{prediction}}"

  fpred_brt1_corr:
    label: "\\vtop{\\hbox{Bkg. correction}\\hbox{from BRT1}}"

