obs: # This key is the type of process. Must be one of [obs, bkg, sig]
  obs: # This key needs to be there in the input yaml
    label: "Data"

bkg:
  misid:
    label: "Background"
    color: "#92dadd"
  
  # Will be used for getting the total bkg and uncertainty for plotting
  # Will not be added to the table if there is only one bkg source
  total_bkg:
    label: "Total bkg."
    color: "#000000"

sig:
  SMS-TStauStau_MStau-100_ctau-50mm_mLSP-1:
      label: "\\vtop{\\hbox{$m_{\\PSGt}(100)$}\\hbox{$c\\tau_{0}(50)$}}"
      rootlabel: "m_{#tilde{#tau}} = 100 GeV, c#tau_{0} = 50 mm"
      color: "#c91f16"
      linestyle: 7
  
  SMS-TStauStau_MStau-100_ctau-100mm_mLSP-1:
    label: "\\vtop{\\hbox{$m_{\\PSGt}(100)$}\\hbox{$c\\tau_{0}(100)$}}"
    rootlabel: "m_{#tilde{#tau}} = 100 GeV, c#tau_{0} = 100 mm"
    color: "#c91f16"
    linestyle: 3
  
  SMS-TStauStau_MStau-200_ctau-50mm_mLSP-1:
    label: "\\vtop{\\hbox{$m_{\\PSGt}(200)$}\\hbox{$c\\tau_{0}(50)$}}"
    rootlabel: "m_{#tilde{#tau}} = 200 GeV, c#tau_{0} = 50 mm"
    color: "#1845fb"
    linestyle: 7
  
  SMS-TStauStau_MStau-200_ctau-100mm_mLSP-1:
    label: "\\vtop{\\hbox{$m_{\\PSGt}(200)$}\\hbox{$c\\tau_{0}(100)$}}"
    rootlabel: "m_{#tilde{#tau}} = 200 GeV, c#tau_{0} = 100 mm"
    color: "#1845fb"
    linestyle: 3

plot_bkgs: ["misid"]

bin_header: "\\vtop{\\hbox{BRT1}\\hbox{bins}}"
bin_header_root: "BRT1 bins"
plot_bins: [3, 4, 5, 6, 7, 8, 9, 10]

bins:
  3:
    label: 1
  4:
    label: 2
  5:
    label: 3
  6:
    label: 4
  7:
    label: 5
  8:
    label: 6
  9:
    label: 7
  10:
    label: 8
  total:
    label: "Total"

centerlabelx: true
logy: true
yrange_ratio: [0, 2]
ndivisionsy_ratio: [2, 5, 0]
group_sigs: true