procs:
  SMS-TStauStau_MStau-100_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '1'
    samples:
    - SMS-TStauStau_MStau-100_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-100_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '1'
    samples:
    - SMS-TStauStau_MStau-100_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-100_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '1'
    samples:
    - SMS-TStauStau_MStau-100_ctau-100mm_mLSP-1
  #SMS-TStauStau_MStau-100_ctau-300mm_mLSP-1_from_ctau-1000mm:
  #  ismc: true
  #  issusy: true
  #  xsnorm: true
  #  scaleby: '1'
  #  samples:
  #  - SMS-TStauStau_MStau-100_ctau-300mm_mLSP-1_from_ctau-1000mm
  SMS-TStauStau_MStau-200_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '1'
    samples:
    - SMS-TStauStau_MStau-200_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-200_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '1'
    samples:
    - SMS-TStauStau_MStau-200_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-200_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '1'
    samples:
    - SMS-TStauStau_MStau-200_ctau-100mm_mLSP-1
  #SMS-TStauStau_MStau-200_ctau-300mm_mLSP-1_from_ctau-1000mm:
  #  ismc: true
  #  issusy: true
  #  xsnorm: true
  #  scaleby: '1'
  #  samples:
  #  - SMS-TStauStau_MStau-200_ctau-300mm_mLSP-1_from_ctau-1000mm
  SMS-TStauStau_MStau-300_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '1'
    samples:
    - SMS-TStauStau_MStau-300_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-300_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '1'
    samples:
    - SMS-TStauStau_MStau-300_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-300_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '1'
    samples:
    - SMS-TStauStau_MStau-300_ctau-100mm_mLSP-1
  #SMS-TStauStau_MStau-300_ctau-300mm_mLSP-1_from_ctau-1000mm:
  #  ismc: true
  #  issusy: true
  #  xsnorm: true
  #  scaleby: '1'
  #  samples:
  #  - SMS-TStauStau_MStau-300_ctau-300mm_mLSP-1_from_ctau-1000mm
