analysis: llstau_maximally-mixed
channel: BRT1
era: 2016_postVFP
lumi: 16.8
obs:
  scaleby: '1'
  samples:
    - DATA_MET
  histfile: /data/dust/user/sobhatta/work/LongLivedStaus/shedprog_2017-studies/LLStaus_Run2/Analysis/output/2016post/output_signal/signal_v12/hists/Cut_018_ht_soft_forward_cut_binning_schema_pass.root
  nominal: nominal/bin1/hist
sig:
  loadconfig: configs/limits/sig_procs_for-BRT1.yaml
  xsecfile: /data/dust/user/sobhatta/work/LongLivedStaus/LLStaus_Run2/Analysis/configs/crosssections_stau_maximally-mixed_hepi-fast.csv
  histfile: /data/dust/user/sobhatta/work/LongLivedStaus/shedprog_2017-studies/LLStaus_Run2/Analysis/output/2016post/output_signal/signal_v12/hists/Cut_018_ht_soft_forward_cut_binning_schema_pass.root
  cutflowsfile: /data/dust/user/sobhatta/work/LongLivedStaus/shedprog_2017-studies/LLStaus_Run2/Analysis/output/2016post/output_signal/signal_v12/cutflows.json
  neventkey: all.BeforeCuts
  neventkey_lifetime_reweighting: all.sig_lifetime_reweighting
  scaleby_allprocs: 0.9*0.9
  nominal: nominal/bin1/hist
bkg:
  procs:
    misid:
      ismc: false
      scaleby: '1'
      samples:
        - DATA_MET
      histfile: /data/dust/user/sobhatta/work/LongLivedStaus/shedprog_2017-studies/LLStaus_Run2/Analysis/output/2016post/output_signal/signal_v12/hists/Cut_018_ht_soft_forward_cut_binning_schema_yield_bin0to1.root
      nominal: nominal/hist
      alpha: 0.054
  xsecfile: /data/dust/user/sobhatta/work/LongLivedStaus/LLStaus_Run2/Analysis/configs/crosssections.json
  cutflowsfile: /data/dust/user/sobhatta/work/LongLivedStaus/shedprog_2017-studies/LLStaus_Run2/Analysis/output/2016post/output_signal/signal_v12/cutflows.json
  neventkey: all.BeforeCuts
systcombos:
  lumi:
    procs:
      sig:
        - sig
      bkg: []
    names:
      - lumi_corr161718
      - lumi_uncorr
systematics:
  lumi_corr161718:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: true
    u: 1.006
    d: 0.994
  lumi_uncorr:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: false
    u: 1.01
    d: 0.99
  met_trigger:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: false
    u:
      '*': MET_trigger_sfs_up/bin1/hist
    d:
      '*': MET_trigger_sfs_down/bin1/hist
  distauid:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: false
    u:
      '*': signal_eff_unc_up/bin1/hist
    d:
      '*': signal_eff_unc_down/bin1/hist
  uncl_met:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: false
    u:
      '*': UncMET_up/bin1/hist
    d:
      '*': UncMET_down/bin1/hist
  pileup:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: false
    u:
      '*': pileup_up/bin1/hist
    d:
      '*': pileup_down/bin1/hist
  l1_prefiring:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: true
    u:
      '*': L1prefiring_up/bin1/hist
    d:
      '*': L1prefiring_down/bin1/hist
  ren_scale:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: true
    u:
      '*': MEren_up/bin1/hist
    d:
      '*': MEren_down/bin1/hist
  fac_scale:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: true
    u:
      '*': MEfac_up/bin1/hist
    d:
      '*': MEfac_down/bin1/hist
  pdf:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: true
    u:
      '*': PDF_up/bin1/hist
    d:
      '*': PDF_down/bin1/hist
  jes:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: false
    u:
      '*': Junc_up/bin1/hist
    d:
      '*': Junc_down/bin1/hist
  jer:
    procs:
      sig:
        - sig
      bkg: []
    iseracorr: false
    u:
      '*': Jer_up/bin1/hist
    d:
      '*': Jer_down/bin1/hist
  fr_stat:
    iseracorr: false
    procs:
      sig: []
      bkg:
        - misid
    u:
      '*': stat_up/hist
    d:
      '*': stat_down/hist
  fr_region:
    iseracorr: true
    procs:
      sig: []
      bkg:
        - misid
    u:
      '*': sys_up/hist
    d:
      '*': sys_down/hist
rebin: null
binstart: 3
nbins: 8
